apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicename }}-svc
  labels:
    app: {{ .Values.servicename }}-svc
spec:
  ports:
  - port: 8002
    protocol: TCP
    targetPort: 5000
    name: http
  selector:
    app: {{ .Values.servicename }}