apiVersion: v1
kind: Service
metadata:
  name: showtimes-svc
  labels:
    app: showtimes-svc
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 5000
    name: http
  selector:
    app: showtimes