apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookings
  labels:
    app: bookings
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: bookings
  template:
    metadata:
      labels:
        app: bookings
    spec:
      containers:
      - name: bookings
        image: vedaprasad/bookings
        imagePullPolicy: Always
