name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout repo

    - name: Generate build number
      uses: einaregilsson/build-number@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image for bookings
      run: cd $GITHUB_WORKSPACE/microservices/bookings/ && docker build -t vedaprasad/bookings:${BUILD_NUMBER} .

    - name: Push bookings Docker image
      run: docker push vedaprasad/bookings:${BUILD_NUMBER}




    